IF DEFINED AUTODEBUG GOTO :KONIEC 

:PYTANIE
SET /P AUTODEBUG="Pokazywac dodatkowo problemy w trakcie pracy? [t/n]"
IF NOT %AUTODEBUG%==t ( IF NOT %AUTODEBUG%==n GOTO :PYTANIE )

:KONIEC
IF %AUTODEBUG%==t SET AUTODEBUG=1
IF %AUTODEBUG%==n SET AUTODEBUG=0 
